apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: fitness-support
profiles:
  # - name: dev
  #   manifests:
  #     rawYaml:
  #       - run-dev.yaml
  - name: prod
    manifests:
      rawYaml:
        - run-prod.yaml
deploy:
  cloudrun: {}
